# Generated by Django 2.0.13 on 2019-09-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0002_asistencia_permiso'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsabilidad',
            old_name='empleado',
            new_name='empleados',
        ),
        migrations.RenameField(
            model_name='responsabilidad',
            old_name='rol',
            new_name='roles',
        ),
    ]
