# Generated by Django 2.0.13 on 2019-09-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RH', '0003_auto_20190902_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsabilidad',
            name='empleados',
            field=models.ManyToManyField(blank=True, null=True, to='RH.Empleado'),
        ),
        migrations.AlterField(
            model_name='responsabilidad',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, to='RH.Rol'),
        ),
    ]
